/* automatically generated by rust-bindgen 0.59.2 */

/* some platform specified defines adjusted by hand */
pub const __GNUC_VA_LIST: ViUInt32 = 1;
pub const _VI_ERROR: ViInt32 = -2147483648;
pub const VI_SUCCESS: ViUInt32 = 0;
pub const VI_NULL: ViUInt32 = 0;
pub const VI_TRUE: ViUInt32 = 1;
pub const VI_FALSE: ViUInt32 = 0;
pub const VI_SPEC_VERSION: ViUInt32 = 7340288;
pub const VI_ATTR_RSRC_CLASS: ViUInt32 = 3221159937;
pub const VI_ATTR_RSRC_NAME: ViUInt32 = 3221159938;
pub const VI_ATTR_RSRC_IMPL_VERSION: ViUInt32 = 1073676291;
pub const VI_ATTR_RSRC_LOCK_STATE: ViUInt32 = 1073676292;
pub const VI_ATTR_MAX_QUEUE_LENGTH: ViUInt32 = 1073676293;
pub const VI_ATTR_USER_DATA_32: ViUInt32 = 1073676295;
pub const VI_ATTR_FDC_CHNL: ViUInt32 = 1073676301;
pub const VI_ATTR_FDC_MODE: ViUInt32 = 1073676303;
pub const VI_ATTR_FDC_GEN_SIGNAL_EN: ViUInt32 = 1073676305;
pub const VI_ATTR_FDC_USE_PAIR: ViUInt32 = 1073676307;
pub const VI_ATTR_SEND_END_EN: ViUInt32 = 1073676310;
pub const VI_ATTR_TERMCHAR: ViUInt32 = 1073676312;
pub const VI_ATTR_TMO_VALUE: ViUInt32 = 1073676314;
pub const VI_ATTR_GPIB_READDR_EN: ViUInt32 = 1073676315;
pub const VI_ATTR_IO_PROT: ViUInt32 = 1073676316;
pub const VI_ATTR_DMA_ALLOW_EN: ViUInt32 = 1073676318;
pub const VI_ATTR_ASRL_BAUD: ViUInt32 = 1073676321;
pub const VI_ATTR_ASRL_DATA_BITS: ViUInt32 = 1073676322;
pub const VI_ATTR_ASRL_PARITY: ViUInt32 = 1073676323;
pub const VI_ATTR_ASRL_STOP_BITS: ViUInt32 = 1073676324;
pub const VI_ATTR_ASRL_FLOW_CNTRL: ViUInt32 = 1073676325;
pub const VI_ATTR_RD_BUF_OPER_MODE: ViUInt32 = 1073676330;
pub const VI_ATTR_RD_BUF_SIZE: ViUInt32 = 1073676331;
pub const VI_ATTR_WR_BUF_OPER_MODE: ViUInt32 = 1073676333;
pub const VI_ATTR_WR_BUF_SIZE: ViUInt32 = 1073676334;
pub const VI_ATTR_SUPPRESS_END_EN: ViUInt32 = 1073676342;
pub const VI_ATTR_TERMCHAR_EN: ViUInt32 = 1073676344;
pub const VI_ATTR_DEST_ACCESS_PRIV: ViUInt32 = 1073676345;
pub const VI_ATTR_DEST_BYTE_ORDER: ViUInt32 = 1073676346;
pub const VI_ATTR_SRC_ACCESS_PRIV: ViUInt32 = 1073676348;
pub const VI_ATTR_SRC_BYTE_ORDER: ViUInt32 = 1073676349;
pub const VI_ATTR_SRC_INCREMENT: ViUInt32 = 1073676352;
pub const VI_ATTR_DEST_INCREMENT: ViUInt32 = 1073676353;
pub const VI_ATTR_WIN_ACCESS_PRIV: ViUInt32 = 1073676357;
pub const VI_ATTR_WIN_BYTE_ORDER: ViUInt32 = 1073676359;
pub const VI_ATTR_GPIB_ATN_STATE: ViUInt32 = 1073676375;
pub const VI_ATTR_GPIB_ADDR_STATE: ViUInt32 = 1073676380;
pub const VI_ATTR_GPIB_CIC_STATE: ViUInt32 = 1073676382;
pub const VI_ATTR_GPIB_NDAC_STATE: ViUInt32 = 1073676386;
pub const VI_ATTR_GPIB_SRQ_STATE: ViUInt32 = 1073676391;
pub const VI_ATTR_GPIB_SYS_CNTRL_STATE: ViUInt32 = 1073676392;
pub const VI_ATTR_GPIB_HS488_CBL_LEN: ViUInt32 = 1073676393;
pub const VI_ATTR_CMDR_LA: ViUInt32 = 1073676395;
pub const VI_ATTR_VXI_DEV_CLASS: ViUInt32 = 1073676396;
pub const VI_ATTR_MAINFRAME_LA: ViUInt32 = 1073676400;
pub const VI_ATTR_MANF_NAME: ViUInt32 = 3221160050;
pub const VI_ATTR_MODEL_NAME: ViUInt32 = 3221160055;
pub const VI_ATTR_VXI_VME_INTR_STATUS: ViUInt32 = 1073676427;
pub const VI_ATTR_VXI_TRIG_STATUS: ViUInt32 = 1073676429;
pub const VI_ATTR_VXI_VME_SYSFAIL_STATE: ViUInt32 = 1073676436;
pub const VI_ATTR_WIN_BASE_ADDR_32: ViUInt32 = 1073676440;
pub const VI_ATTR_WIN_SIZE_32: ViUInt32 = 1073676442;
pub const VI_ATTR_ASRL_AVAIL_NUM: ViUInt32 = 1073676460;
pub const VI_ATTR_MEM_BASE_32: ViUInt32 = 1073676461;
pub const VI_ATTR_ASRL_CTS_STATE: ViUInt32 = 1073676462;
pub const VI_ATTR_ASRL_DCD_STATE: ViUInt32 = 1073676463;
pub const VI_ATTR_ASRL_DSR_STATE: ViUInt32 = 1073676465;
pub const VI_ATTR_ASRL_DTR_STATE: ViUInt32 = 1073676466;
pub const VI_ATTR_ASRL_END_IN: ViUInt32 = 1073676467;
pub const VI_ATTR_ASRL_END_OUT: ViUInt32 = 1073676468;
pub const VI_ATTR_ASRL_REPLACE_CHAR: ViUInt32 = 1073676478;
pub const VI_ATTR_ASRL_RI_STATE: ViUInt32 = 1073676479;
pub const VI_ATTR_ASRL_RTS_STATE: ViUInt32 = 1073676480;
pub const VI_ATTR_ASRL_XON_CHAR: ViUInt32 = 1073676481;
pub const VI_ATTR_ASRL_XOFF_CHAR: ViUInt32 = 1073676482;
pub const VI_ATTR_WIN_ACCESS: ViUInt32 = 1073676483;
pub const VI_ATTR_RM_SESSION: ViUInt32 = 1073676484;
pub const VI_ATTR_VXI_LA: ViUInt32 = 1073676501;
pub const VI_ATTR_MANF_ID: ViUInt32 = 1073676505;
pub const VI_ATTR_MEM_SIZE_32: ViUInt32 = 1073676509;
pub const VI_ATTR_MEM_SPACE: ViUInt32 = 1073676510;
pub const VI_ATTR_MODEL_CODE: ViUInt32 = 1073676511;
pub const VI_ATTR_SLOT: ViUInt32 = 1073676520;
pub const VI_ATTR_INTF_INST_NAME: ViUInt32 = 3221160169;
pub const VI_ATTR_IMMEDIATE_SERV: ViUInt32 = 1073676544;
pub const VI_ATTR_INTF_PARENT_NUM: ViUInt32 = 1073676545;
pub const VI_ATTR_RSRC_SPEC_VERSION: ViUInt32 = 1073676656;
pub const VI_ATTR_INTF_TYPE: ViUInt32 = 1073676657;
pub const VI_ATTR_GPIB_PRIMARY_ADDR: ViUInt32 = 1073676658;
pub const VI_ATTR_GPIB_SECONDARY_ADDR: ViUInt32 = 1073676659;
pub const VI_ATTR_RSRC_MANF_NAME: ViUInt32 = 3221160308;
pub const VI_ATTR_RSRC_MANF_ID: ViUInt32 = 1073676661;
pub const VI_ATTR_INTF_NUM: ViUInt32 = 1073676662;
pub const VI_ATTR_TRIG_ID: ViUInt32 = 1073676663;
pub const VI_ATTR_GPIB_REN_STATE: ViUInt32 = 1073676673;
pub const VI_ATTR_GPIB_UNADDR_EN: ViUInt32 = 1073676676;
pub const VI_ATTR_DEV_STATUS_BYTE: ViUInt32 = 1073676681;
pub const VI_ATTR_FILE_APPEND_EN: ViUInt32 = 1073676690;
pub const VI_ATTR_VXI_TRIG_SUPPORT: ViUInt32 = 1073676692;
pub const VI_ATTR_TCPIP_ADDR: ViUInt32 = 3221160341;
pub const VI_ATTR_TCPIP_HOSTNAME: ViUInt32 = 3221160342;
pub const VI_ATTR_TCPIP_PORT: ViUInt32 = 1073676695;
pub const VI_ATTR_TCPIP_DEVICE_NAME: ViUInt32 = 3221160345;
pub const VI_ATTR_TCPIP_NODELAY: ViUInt32 = 1073676698;
pub const VI_ATTR_TCPIP_KEEPALIVE: ViUInt32 = 1073676699;
pub const VI_ATTR_4882_COMPLIANT: ViUInt32 = 1073676703;
pub const VI_ATTR_USB_SERIAL_NUM: ViUInt32 = 3221160352;
pub const VI_ATTR_USB_INTFC_NUM: ViUInt32 = 1073676705;
pub const VI_ATTR_USB_PROTOCOL: ViUInt32 = 1073676711;
pub const VI_ATTR_USB_MAX_INTR_SIZE: ViUInt32 = 1073676719;
pub const VI_ATTR_PXI_DEV_NUM: ViUInt32 = 1073676801;
pub const VI_ATTR_PXI_FUNC_NUM: ViUInt32 = 1073676802;
pub const VI_ATTR_PXI_BUS_NUM: ViUInt32 = 1073676805;
pub const VI_ATTR_PXI_CHASSIS: ViUInt32 = 1073676806;
pub const VI_ATTR_PXI_SLOTPATH: ViUInt32 = 3221160455;
pub const VI_ATTR_PXI_SLOT_LBUS_LEFT: ViUInt32 = 1073676808;
pub const VI_ATTR_PXI_SLOT_LBUS_RIGHT: ViUInt32 = 1073676809;
pub const VI_ATTR_PXI_TRIG_BUS: ViUInt32 = 1073676810;
pub const VI_ATTR_PXI_STAR_TRIG_BUS: ViUInt32 = 1073676811;
pub const VI_ATTR_PXI_STAR_TRIG_LINE: ViUInt32 = 1073676812;
pub const VI_ATTR_PXI_SRC_TRIG_BUS: ViUInt32 = 1073676813;
pub const VI_ATTR_PXI_DEST_TRIG_BUS: ViUInt32 = 1073676814;
pub const VI_ATTR_PXI_MEM_TYPE_BAR0: ViUInt32 = 1073676817;
pub const VI_ATTR_PXI_MEM_TYPE_BAR1: ViUInt32 = 1073676818;
pub const VI_ATTR_PXI_MEM_TYPE_BAR2: ViUInt32 = 1073676819;
pub const VI_ATTR_PXI_MEM_TYPE_BAR3: ViUInt32 = 1073676820;
pub const VI_ATTR_PXI_MEM_TYPE_BAR4: ViUInt32 = 1073676821;
pub const VI_ATTR_PXI_MEM_TYPE_BAR5: ViUInt32 = 1073676822;
pub const VI_ATTR_PXI_MEM_BASE_BAR0_32: ViUInt32 = 1073676833;
pub const VI_ATTR_PXI_MEM_BASE_BAR1_32: ViUInt32 = 1073676834;
pub const VI_ATTR_PXI_MEM_BASE_BAR2_32: ViUInt32 = 1073676835;
pub const VI_ATTR_PXI_MEM_BASE_BAR3_32: ViUInt32 = 1073676836;
pub const VI_ATTR_PXI_MEM_BASE_BAR4_32: ViUInt32 = 1073676837;
pub const VI_ATTR_PXI_MEM_BASE_BAR5_32: ViUInt32 = 1073676838;
pub const VI_ATTR_PXI_MEM_BASE_BAR0_64: ViUInt32 = 1073676840;
pub const VI_ATTR_PXI_MEM_BASE_BAR1_64: ViUInt32 = 1073676841;
pub const VI_ATTR_PXI_MEM_BASE_BAR2_64: ViUInt32 = 1073676842;
pub const VI_ATTR_PXI_MEM_BASE_BAR3_64: ViUInt32 = 1073676843;
pub const VI_ATTR_PXI_MEM_BASE_BAR4_64: ViUInt32 = 1073676844;
pub const VI_ATTR_PXI_MEM_BASE_BAR5_64: ViUInt32 = 1073676845;
pub const VI_ATTR_PXI_MEM_SIZE_BAR0_32: ViUInt32 = 1073676849;
pub const VI_ATTR_PXI_MEM_SIZE_BAR1_32: ViUInt32 = 1073676850;
pub const VI_ATTR_PXI_MEM_SIZE_BAR2_32: ViUInt32 = 1073676851;
pub const VI_ATTR_PXI_MEM_SIZE_BAR3_32: ViUInt32 = 1073676852;
pub const VI_ATTR_PXI_MEM_SIZE_BAR4_32: ViUInt32 = 1073676853;
pub const VI_ATTR_PXI_MEM_SIZE_BAR5_32: ViUInt32 = 1073676854;
pub const VI_ATTR_PXI_MEM_SIZE_BAR0_64: ViUInt32 = 1073676856;
pub const VI_ATTR_PXI_MEM_SIZE_BAR1_64: ViUInt32 = 1073676857;
pub const VI_ATTR_PXI_MEM_SIZE_BAR2_64: ViUInt32 = 1073676858;
pub const VI_ATTR_PXI_MEM_SIZE_BAR3_64: ViUInt32 = 1073676859;
pub const VI_ATTR_PXI_MEM_SIZE_BAR4_64: ViUInt32 = 1073676860;
pub const VI_ATTR_PXI_MEM_SIZE_BAR5_64: ViUInt32 = 1073676861;
pub const VI_ATTR_PXI_IS_EXPRESS: ViUInt32 = 1073676864;
pub const VI_ATTR_PXI_SLOT_LWIDTH: ViUInt32 = 1073676865;
pub const VI_ATTR_PXI_MAX_LWIDTH: ViUInt32 = 1073676866;
pub const VI_ATTR_PXI_ACTUAL_LWIDTH: ViUInt32 = 1073676867;
pub const VI_ATTR_PXI_DSTAR_BUS: ViUInt32 = 1073676868;
pub const VI_ATTR_PXI_DSTAR_SET: ViUInt32 = 1073676869;
pub const VI_ATTR_PXI_ALLOW_WRITE_COMBINE: ViUInt32 = 1073676870;
pub const VI_ATTR_TCPIP_SERVER_CERT_ISSUER_NAME: ViUInt32 = 3221160560;
pub const VI_ATTR_TCPIP_SERVER_CERT_SUBJECT_NAME: ViUInt32 = 3221160561;
pub const VI_ATTR_TCPIP_SERVER_CERT_EXPIRATION_DATE: ViUInt32 = 3221160562;
pub const VI_ATTR_TCPIP_SERVER_CERT_IS_PERPETUAL: ViUInt32 = 1073676915;
pub const VI_ATTR_TCPIP_SASL_MECHANISM: ViUInt32 = 3221160564;
pub const VI_ATTR_TCPIP_TLS_CIPHER_SUITE: ViUInt32 = 3221160565;
pub const VI_ATTR_TCPIP_HISLIP_OVERLAP_EN: ViUInt32 = 1073677056;
pub const VI_ATTR_TCPIP_HISLIP_VERSION: ViUInt32 = 1073677057;
pub const VI_ATTR_TCPIP_HISLIP_MAX_MESSAGE_KB: ViUInt32 = 1073677058;
pub const VI_ATTR_TCPIP_IS_HISLIP: ViUInt32 = 1073677059;
pub const VI_ATTR_TCPIP_HISLIP_ENCRYPTION_EN: ViUInt32 = 1073677060;
pub const VI_ATTR_JOB_ID: ViUInt32 = 1073692678;
pub const VI_ATTR_EVENT_TYPE: ViUInt32 = 1073692688;
pub const VI_ATTR_SIGP_STATUS_ID: ViUInt32 = 1073692689;
pub const VI_ATTR_RECV_TRIG_ID: ViUInt32 = 1073692690;
pub const VI_ATTR_INTR_STATUS_ID: ViUInt32 = 1073692707;
pub const VI_ATTR_STATUS: ViUInt32 = 1073692709;
pub const VI_ATTR_RET_COUNT_32: ViUInt32 = 1073692710;
pub const VI_ATTR_BUFFER: ViUInt32 = 1073692711;
pub const VI_ATTR_RECV_INTR_LEVEL: ViUInt32 = 1073692737;
pub const VI_ATTR_OPER_NAME: ViUInt32 = 3221176386;
pub const VI_ATTR_GPIB_RECV_CIC_STATE: ViUInt32 = 1073693075;
pub const VI_ATTR_RECV_TCPIP_ADDR: ViUInt32 = 3221176728;
pub const VI_ATTR_USB_RECV_INTR_SIZE: ViUInt32 = 1073693104;
pub const VI_ATTR_USB_RECV_INTR_DATA: ViUInt32 = 3221176753;
pub const VI_ATTR_PXI_RECV_INTR_SEQ: ViUInt32 = 1073693248;
pub const VI_ATTR_PXI_RECV_INTR_DATA: ViUInt32 = 1073693249;
pub const VI_ATTR_USER_DATA_64: ViUInt32 = 1073676298;
pub const VI_ATTR_RET_COUNT_64: ViUInt32 = 1073692712;
//pub const VI_ATTR_USER_DATA: ViUInt32 = 1073676298;
//pub const VI_ATTR_RET_COUNT: ViUInt32 = 1073692712;
pub const VI_ATTR_WIN_BASE_ADDR_64: ViUInt32 = 1073676443;
pub const VI_ATTR_WIN_SIZE_64: ViUInt32 = 1073676444;
pub const VI_ATTR_MEM_BASE_64: ViUInt32 = 1073676496;
pub const VI_ATTR_MEM_SIZE_64: ViUInt32 = 1073676497;
//pub const VI_ATTR_WIN_BASE_ADDR: ViUInt32 = 1073676443;
//pub const VI_ATTR_WIN_SIZE: ViUInt32 = 1073676444;
//pub const VI_ATTR_MEM_BASE: ViUInt32 = 1073676496;
//pub const VI_ATTR_MEM_SIZE: ViUInt32 = 1073676497;
//pub const VI_ATTR_PXI_MEM_BASE_BAR0: ViUInt32 = 1073676840;
//pub const VI_ATTR_PXI_MEM_BASE_BAR1: ViUInt32 = 1073676841;
//pub const VI_ATTR_PXI_MEM_BASE_BAR2: ViUInt32 = 1073676842;
//pub const VI_ATTR_PXI_MEM_BASE_BAR3: ViUInt32 = 1073676843;
//pub const VI_ATTR_PXI_MEM_BASE_BAR4: ViUInt32 = 1073676844;
//pub const VI_ATTR_PXI_MEM_BASE_BAR5: ViUInt32 = 1073676845;
//pub const VI_ATTR_PXI_MEM_SIZE_BAR0: ViUInt32 = 1073676856;
//pub const VI_ATTR_PXI_MEM_SIZE_BAR1: ViUInt32 = 1073676857;
//pub const VI_ATTR_PXI_MEM_SIZE_BAR2: ViUInt32 = 1073676858;
//pub const VI_ATTR_PXI_MEM_SIZE_BAR3: ViUInt32 = 1073676859;
//pub const VI_ATTR_PXI_MEM_SIZE_BAR4: ViUInt32 = 1073676860;
//pub const VI_ATTR_PXI_MEM_SIZE_BAR5: ViUInt32 = 1073676861;
pub const VI_EVENT_IO_COMPLETION: ViUInt32 = 1073684489;
pub const VI_EVENT_TRIG: ViUInt32 = 3221168138;
pub const VI_EVENT_SERVICE_REQ: ViUInt32 = 1073684491;
pub const VI_EVENT_CLEAR: ViUInt32 = 1073684493;
pub const VI_EVENT_EXCEPTION: ViUInt32 = 3221168142;
pub const VI_EVENT_GPIB_CIC: ViUInt32 = 1073684498;
pub const VI_EVENT_GPIB_TALK: ViUInt32 = 1073684499;
pub const VI_EVENT_GPIB_LISTEN: ViUInt32 = 1073684500;
pub const VI_EVENT_VXI_VME_SYSFAIL: ViUInt32 = 1073684509;
pub const VI_EVENT_VXI_VME_SYSRESET: ViUInt32 = 1073684510;
pub const VI_EVENT_VXI_SIGP: ViUInt32 = 1073684512;
pub const VI_EVENT_VXI_VME_INTR: ViUInt32 = 3221168161;
pub const VI_EVENT_PXI_INTR: ViUInt32 = 1073684514;
pub const VI_EVENT_TCPIP_CONNECT: ViUInt32 = 1073684534;
pub const VI_EVENT_USB_INTR: ViUInt32 = 1073684535;
pub const VI_ALL_ENABLED_EVENTS: ViUInt32 = 1073709055;
pub const VI_SUCCESS_EVENT_EN: ViUInt32 = 1073676290;
pub const VI_SUCCESS_EVENT_DIS: ViUInt32 = 1073676291;
pub const VI_SUCCESS_QUEUE_EMPTY: ViUInt32 = 1073676292;
pub const VI_SUCCESS_TERM_CHAR: ViUInt32 = 1073676293;
pub const VI_SUCCESS_MAX_CNT: ViUInt32 = 1073676294;
pub const VI_SUCCESS_DEV_NPRESENT: ViUInt32 = 1073676413;
pub const VI_SUCCESS_TRIG_MAPPED: ViUInt32 = 1073676414;
pub const VI_SUCCESS_QUEUE_NEMPTY: ViUInt32 = 1073676416;
pub const VI_SUCCESS_NCHAIN: ViUInt32 = 1073676440;
pub const VI_SUCCESS_NESTED_SHARED: ViUInt32 = 1073676441;
pub const VI_SUCCESS_NESTED_EXCLUSIVE: ViUInt32 = 1073676442;
pub const VI_SUCCESS_SYNC: ViUInt32 = 1073676443;
pub const VI_WARN_QUEUE_OVERFLOW: ViUInt32 = 1073676300;
pub const VI_WARN_CONFIG_NLOADED: ViUInt32 = 1073676407;
pub const VI_WARN_NULL_OBJECT: ViUInt32 = 1073676418;
pub const VI_WARN_NSUP_ATTR_STATE: ViUInt32 = 1073676420;
pub const VI_WARN_UNKNOWN_STATUS: ViUInt32 = 1073676421;
pub const VI_WARN_NSUP_BUF: ViUInt32 = 1073676424;
pub const VI_WARN_EXT_FUNC_NIMPL: ViUInt32 = 1073676457;
pub const VI_WARN_SERVER_CERT_UNTRUSTED: ViUInt32 = 1073676528;
pub const VI_ERROR_SYSTEM_ERROR: ViInt32 = -1073807360;
pub const VI_ERROR_INV_OBJECT: ViInt32 = -1073807346;
pub const VI_ERROR_RSRC_LOCKED: ViInt32 = -1073807345;
pub const VI_ERROR_INV_EXPR: ViInt32 = -1073807344;
pub const VI_ERROR_RSRC_NFOUND: ViInt32 = -1073807343;
pub const VI_ERROR_INV_RSRC_NAME: ViInt32 = -1073807342;
pub const VI_ERROR_INV_ACC_MODE: ViInt32 = -1073807341;
pub const VI_ERROR_TMO: ViInt32 = -1073807339;
pub const VI_ERROR_CLOSING_FAILED: ViInt32 = -1073807338;
pub const VI_ERROR_INV_DEGREE: ViInt32 = -1073807333;
pub const VI_ERROR_INV_JOB_ID: ViInt32 = -1073807332;
pub const VI_ERROR_NSUP_ATTR: ViInt32 = -1073807331;
pub const VI_ERROR_NSUP_ATTR_STATE: ViInt32 = -1073807330;
pub const VI_ERROR_ATTR_READONLY: ViInt32 = -1073807329;
pub const VI_ERROR_INV_LOCK_TYPE: ViInt32 = -1073807328;
pub const VI_ERROR_INV_ACCESS_KEY: ViInt32 = -1073807327;
pub const VI_ERROR_INV_EVENT: ViInt32 = -1073807322;
pub const VI_ERROR_INV_MECH: ViInt32 = -1073807321;
pub const VI_ERROR_HNDLR_NINSTALLED: ViInt32 = -1073807320;
pub const VI_ERROR_INV_HNDLR_REF: ViInt32 = -1073807319;
pub const VI_ERROR_INV_CONTEXT: ViInt32 = -1073807318;
pub const VI_ERROR_NENABLED: ViInt32 = -1073807313;
pub const VI_ERROR_ABORT: ViInt32 = -1073807312;
pub const VI_ERROR_RAW_WR_PROT_VIOL: ViInt32 = -1073807308;
pub const VI_ERROR_RAW_RD_PROT_VIOL: ViInt32 = -1073807307;
pub const VI_ERROR_OUTP_PROT_VIOL: ViInt32 = -1073807306;
pub const VI_ERROR_INP_PROT_VIOL: ViInt32 = -1073807305;
pub const VI_ERROR_BERR: ViInt32 = -1073807304;
pub const VI_ERROR_IN_PROGRESS: ViInt32 = -1073807303;
pub const VI_ERROR_INV_SETUP: ViInt32 = -1073807302;
pub const VI_ERROR_QUEUE_ERROR: ViInt32 = -1073807301;
pub const VI_ERROR_ALLOC: ViInt32 = -1073807300;
pub const VI_ERROR_INV_MASK: ViInt32 = -1073807299;
pub const VI_ERROR_IO: ViInt32 = -1073807298;
pub const VI_ERROR_INV_FMT: ViInt32 = -1073807297;
pub const VI_ERROR_NSUP_FMT: ViInt32 = -1073807295;
pub const VI_ERROR_LINE_IN_USE: ViInt32 = -1073807294;
pub const VI_ERROR_LINE_NRESERVED: ViInt32 = -1073807293;
pub const VI_ERROR_NSUP_MODE: ViInt32 = -1073807290;
pub const VI_ERROR_SRQ_NOCCURRED: ViInt32 = -1073807286;
pub const VI_ERROR_INV_SPACE: ViInt32 = -1073807282;
pub const VI_ERROR_INV_OFFSET: ViInt32 = -1073807279;
pub const VI_ERROR_INV_WIDTH: ViInt32 = -1073807278;
pub const VI_ERROR_NSUP_OFFSET: ViInt32 = -1073807276;
pub const VI_ERROR_NSUP_VAR_WIDTH: ViInt32 = -1073807275;
pub const VI_ERROR_WINDOW_NMAPPED: ViInt32 = -1073807273;
pub const VI_ERROR_RESP_PENDING: ViInt32 = -1073807271;
pub const VI_ERROR_NLISTENERS: ViInt32 = -1073807265;
pub const VI_ERROR_NCIC: ViInt32 = -1073807264;
pub const VI_ERROR_NSYS_CNTLR: ViInt32 = -1073807263;
pub const VI_ERROR_NSUP_OPER: ViInt32 = -1073807257;
pub const VI_ERROR_INTR_PENDING: ViInt32 = -1073807256;
pub const VI_ERROR_ASRL_PARITY: ViInt32 = -1073807254;
pub const VI_ERROR_ASRL_FRAMING: ViInt32 = -1073807253;
pub const VI_ERROR_ASRL_OVERRUN: ViInt32 = -1073807252;
pub const VI_ERROR_TRIG_NMAPPED: ViInt32 = -1073807250;
pub const VI_ERROR_NSUP_ALIGN_OFFSET: ViInt32 = -1073807248;
pub const VI_ERROR_USER_BUF: ViInt32 = -1073807247;
pub const VI_ERROR_RSRC_BUSY: ViInt32 = -1073807246;
pub const VI_ERROR_NSUP_WIDTH: ViInt32 = -1073807242;
pub const VI_ERROR_INV_PARAMETER: ViInt32 = -1073807240;
pub const VI_ERROR_INV_PROT: ViInt32 = -1073807239;
pub const VI_ERROR_INV_SIZE: ViInt32 = -1073807237;
pub const VI_ERROR_WINDOW_MAPPED: ViInt32 = -1073807232;
pub const VI_ERROR_NIMPL_OPER: ViInt32 = -1073807231;
pub const VI_ERROR_INV_LENGTH: ViInt32 = -1073807229;
pub const VI_ERROR_INV_MODE: ViInt32 = -1073807215;
pub const VI_ERROR_SESN_NLOCKED: ViInt32 = -1073807204;
pub const VI_ERROR_MEM_NSHARED: ViInt32 = -1073807203;
pub const VI_ERROR_LIBRARY_NFOUND: ViInt32 = -1073807202;
pub const VI_ERROR_NSUP_INTR: ViInt32 = -1073807201;
pub const VI_ERROR_INV_LINE: ViInt32 = -1073807200;
pub const VI_ERROR_FILE_ACCESS: ViInt32 = -1073807199;
pub const VI_ERROR_FILE_IO: ViInt32 = -1073807198;
pub const VI_ERROR_NSUP_LINE: ViInt32 = -1073807197;
pub const VI_ERROR_NSUP_MECH: ViInt32 = -1073807196;
pub const VI_ERROR_INTF_NUM_NCONFIG: ViInt32 = -1073807195;
pub const VI_ERROR_CONN_LOST: ViInt32 = -1073807194;
pub const VI_ERROR_NPERMISSION: ViInt32 = -1073807192;
pub const VI_ERROR_SERVER_CERT: ViInt32 = -1073807184;
pub const VI_FIND_BUFLEN: ViUInt32 = 256;
pub const VI_INTF_GPIB: ViUInt32 = 1;
pub const VI_INTF_VXI: ViUInt32 = 2;
pub const VI_INTF_GPIB_VXI: ViUInt32 = 3;
pub const VI_INTF_ASRL: ViUInt32 = 4;
pub const VI_INTF_PXI: ViUInt32 = 5;
pub const VI_INTF_TCPIP: ViUInt32 = 6;
pub const VI_INTF_USB: ViUInt32 = 7;
pub const VI_PROT_NORMAL: ViUInt32 = 1;
pub const VI_PROT_FDC: ViUInt32 = 2;
pub const VI_PROT_HS488: ViUInt32 = 3;
pub const VI_PROT_4882_STRS: ViUInt32 = 4;
pub const VI_PROT_USBTMC_VENDOR: ViUInt32 = 5;
pub const VI_FDC_NORMAL: ViUInt32 = 1;
pub const VI_FDC_STREAM: ViUInt32 = 2;
pub const VI_LOCAL_SPACE: ViUInt32 = 0;
pub const VI_A16_SPACE: ViUInt32 = 1;
pub const VI_A24_SPACE: ViUInt32 = 2;
pub const VI_A32_SPACE: ViUInt32 = 3;
pub const VI_A64_SPACE: ViUInt32 = 4;
pub const VI_PXI_ALLOC_SPACE: ViUInt32 = 9;
pub const VI_PXI_CFG_SPACE: ViUInt32 = 10;
pub const VI_PXI_BAR0_SPACE: ViUInt32 = 11;
pub const VI_PXI_BAR1_SPACE: ViUInt32 = 12;
pub const VI_PXI_BAR2_SPACE: ViUInt32 = 13;
pub const VI_PXI_BAR3_SPACE: ViUInt32 = 14;
pub const VI_PXI_BAR4_SPACE: ViUInt32 = 15;
pub const VI_PXI_BAR5_SPACE: ViUInt32 = 16;
pub const VI_OPAQUE_SPACE: ViUInt32 = 65535;
pub const VI_UNKNOWN_LA: ViInt32 = -1;
pub const VI_UNKNOWN_SLOT: ViInt32 = -1;
pub const VI_UNKNOWN_LEVEL: ViInt32 = -1;
pub const VI_UNKNOWN_CHASSIS: ViInt32 = -1;
pub const VI_QUEUE: ViUInt32 = 1;
pub const VI_HNDLR: ViUInt32 = 2;
pub const VI_SUSPEND_HNDLR: ViUInt32 = 4;
pub const VI_ALL_MECH: ViUInt32 = 65535;
pub const VI_ANY_HNDLR: ViUInt32 = 0;
pub const VI_TRIG_ALL: ViInt32 = -2;
pub const VI_TRIG_SW: ViInt32 = -1;
pub const VI_TRIG_TTL0: ViUInt32 = 0;
pub const VI_TRIG_TTL1: ViUInt32 = 1;
pub const VI_TRIG_TTL2: ViUInt32 = 2;
pub const VI_TRIG_TTL3: ViUInt32 = 3;
pub const VI_TRIG_TTL4: ViUInt32 = 4;
pub const VI_TRIG_TTL5: ViUInt32 = 5;
pub const VI_TRIG_TTL6: ViUInt32 = 6;
pub const VI_TRIG_TTL7: ViUInt32 = 7;
pub const VI_TRIG_ECL0: ViUInt32 = 8;
pub const VI_TRIG_ECL1: ViUInt32 = 9;
pub const VI_TRIG_ECL2: ViUInt32 = 10;
pub const VI_TRIG_ECL3: ViUInt32 = 11;
pub const VI_TRIG_ECL4: ViUInt32 = 12;
pub const VI_TRIG_ECL5: ViUInt32 = 13;
pub const VI_TRIG_STAR_SLOT1: ViUInt32 = 14;
pub const VI_TRIG_STAR_SLOT2: ViUInt32 = 15;
pub const VI_TRIG_STAR_SLOT3: ViUInt32 = 16;
pub const VI_TRIG_STAR_SLOT4: ViUInt32 = 17;
pub const VI_TRIG_STAR_SLOT5: ViUInt32 = 18;
pub const VI_TRIG_STAR_SLOT6: ViUInt32 = 19;
pub const VI_TRIG_STAR_SLOT7: ViUInt32 = 20;
pub const VI_TRIG_STAR_SLOT8: ViUInt32 = 21;
pub const VI_TRIG_STAR_SLOT9: ViUInt32 = 22;
pub const VI_TRIG_STAR_SLOT10: ViUInt32 = 23;
pub const VI_TRIG_STAR_SLOT11: ViUInt32 = 24;
pub const VI_TRIG_STAR_SLOT12: ViUInt32 = 25;
pub const VI_TRIG_STAR_INSTR: ViUInt32 = 26;
pub const VI_TRIG_PANEL_IN: ViUInt32 = 27;
pub const VI_TRIG_PANEL_OUT: ViUInt32 = 28;
pub const VI_TRIG_STAR_VXI0: ViUInt32 = 29;
pub const VI_TRIG_STAR_VXI1: ViUInt32 = 30;
pub const VI_TRIG_STAR_VXI2: ViUInt32 = 31;
pub const VI_TRIG_TTL8: ViUInt32 = 32;
pub const VI_TRIG_TTL9: ViUInt32 = 33;
pub const VI_TRIG_TTL10: ViUInt32 = 34;
pub const VI_TRIG_TTL11: ViUInt32 = 35;
pub const VI_TRIG_PROT_DEFAULT: ViUInt32 = 0;
pub const VI_TRIG_PROT_ON: ViUInt32 = 1;
pub const VI_TRIG_PROT_OFF: ViUInt32 = 2;
pub const VI_TRIG_PROT_SYNC: ViUInt32 = 5;
pub const VI_TRIG_PROT_RESERVE: ViUInt32 = 6;
pub const VI_TRIG_PROT_UNRESERVE: ViUInt32 = 7;
pub const VI_READ_BUF: ViUInt32 = 1;
pub const VI_WRITE_BUF: ViUInt32 = 2;
pub const VI_READ_BUF_DISCARD: ViUInt32 = 4;
pub const VI_WRITE_BUF_DISCARD: ViUInt32 = 8;
pub const VI_IO_IN_BUF: ViUInt32 = 16;
pub const VI_IO_OUT_BUF: ViUInt32 = 32;
pub const VI_IO_IN_BUF_DISCARD: ViUInt32 = 64;
pub const VI_IO_OUT_BUF_DISCARD: ViUInt32 = 128;
pub const VI_FLUSH_ON_ACCESS: ViUInt32 = 1;
pub const VI_FLUSH_WHEN_FULL: ViUInt32 = 2;
pub const VI_FLUSH_DISABLE: ViUInt32 = 3;
pub const VI_NMAPPED: ViUInt32 = 1;
pub const VI_USE_OPERS: ViUInt32 = 2;
pub const VI_DEREF_ADDR: ViUInt32 = 3;
pub const VI_TMO_IMMEDIATE: ViUInt32 = 0;
pub const VI_TMO_INFINITE: ViUInt32 = 4294967295;
pub const VI_NO_LOCK: ViUInt32 = 0;
pub const VI_EXCLUSIVE_LOCK: ViUInt32 = 1;
pub const VI_SHARED_LOCK: ViUInt32 = 2;
pub const VI_LOAD_CONFIG: ViUInt32 = 4;
pub const VI_NO_SEC_ADDR: ViUInt32 = 65535;
pub const VI_ASRL_PAR_NONE: ViUInt32 = 0;
pub const VI_ASRL_PAR_ODD: ViUInt32 = 1;
pub const VI_ASRL_PAR_EVEN: ViUInt32 = 2;
pub const VI_ASRL_PAR_MARK: ViUInt32 = 3;
pub const VI_ASRL_PAR_SPACE: ViUInt32 = 4;
pub const VI_ASRL_STOP_ONE: ViUInt32 = 10;
pub const VI_ASRL_STOP_ONE5: ViUInt32 = 15;
pub const VI_ASRL_STOP_TWO: ViUInt32 = 20;
pub const VI_ASRL_FLOW_NONE: ViUInt32 = 0;
pub const VI_ASRL_FLOW_XON_XOFF: ViUInt32 = 1;
pub const VI_ASRL_FLOW_RTS_CTS: ViUInt32 = 2;
pub const VI_ASRL_FLOW_DTR_DSR: ViUInt32 = 4;
pub const VI_ASRL_END_NONE: ViUInt32 = 0;
pub const VI_ASRL_END_LAST_BIT: ViUInt32 = 1;
pub const VI_ASRL_END_TERMCHAR: ViUInt32 = 2;
pub const VI_ASRL_END_BREAK: ViUInt32 = 3;
pub const VI_STATE_ASSERTED: ViUInt32 = 1;
pub const VI_STATE_UNASSERTED: ViUInt32 = 0;
pub const VI_STATE_UNKNOWN: ViInt32 = -1;
pub const VI_BIG_ENDIAN: ViUInt32 = 0;
pub const VI_LITTLE_ENDIAN: ViUInt32 = 1;
pub const VI_DATA_PRIV: ViUInt32 = 0;
pub const VI_DATA_NPRIV: ViUInt32 = 1;
pub const VI_PROG_PRIV: ViUInt32 = 2;
pub const VI_PROG_NPRIV: ViUInt32 = 3;
pub const VI_BLCK_PRIV: ViUInt32 = 4;
pub const VI_BLCK_NPRIV: ViUInt32 = 5;
pub const VI_D64_PRIV: ViUInt32 = 6;
pub const VI_D64_NPRIV: ViUInt32 = 7;
pub const VI_D64_2EVME: ViUInt32 = 8;
pub const VI_D64_SST160: ViUInt32 = 9;
pub const VI_D64_SST267: ViUInt32 = 10;
pub const VI_D64_SST320: ViUInt32 = 11;
pub const VI_WIDTH_8: ViUInt32 = 1;
pub const VI_WIDTH_16: ViUInt32 = 2;
pub const VI_WIDTH_32: ViUInt32 = 4;
pub const VI_WIDTH_64: ViUInt32 = 8;
pub const VI_GPIB_REN_DEASSERT: ViUInt32 = 0;
pub const VI_GPIB_REN_ASSERT: ViUInt32 = 1;
pub const VI_GPIB_REN_DEASSERT_GTL: ViUInt32 = 2;
pub const VI_GPIB_REN_ASSERT_ADDRESS: ViUInt32 = 3;
pub const VI_GPIB_REN_ASSERT_LLO: ViUInt32 = 4;
pub const VI_GPIB_REN_ASSERT_ADDRESS_LLO: ViUInt32 = 5;
pub const VI_GPIB_REN_ADDRESS_GTL: ViUInt32 = 6;
pub const VI_GPIB_ATN_DEASSERT: ViUInt32 = 0;
pub const VI_GPIB_ATN_ASSERT: ViUInt32 = 1;
pub const VI_GPIB_ATN_DEASSERT_HANDSHAKE: ViUInt32 = 2;
pub const VI_GPIB_ATN_ASSERT_IMMEDIATE: ViUInt32 = 3;
pub const VI_GPIB_HS488_DISABLED: ViUInt32 = 0;
pub const VI_GPIB_HS488_NIMPL: ViInt32 = -1;
pub const VI_GPIB_UNADDRESSED: ViUInt32 = 0;
pub const VI_GPIB_TALKER: ViUInt32 = 1;
pub const VI_GPIB_LISTENER: ViUInt32 = 2;
pub const VI_VXI_CMD16: ViUInt32 = 512;
pub const VI_VXI_CMD16_RESP16: ViUInt32 = 514;
pub const VI_VXI_RESP16: ViUInt32 = 2;
pub const VI_VXI_CMD32: ViUInt32 = 1024;
pub const VI_VXI_CMD32_RESP16: ViUInt32 = 1026;
pub const VI_VXI_CMD32_RESP32: ViUInt32 = 1028;
pub const VI_VXI_RESP32: ViUInt32 = 4;
pub const VI_ASSERT_SIGNAL: ViInt32 = -1;
pub const VI_ASSERT_USE_ASSIGNED: ViUInt32 = 0;
pub const VI_ASSERT_IRQ1: ViUInt32 = 1;
pub const VI_ASSERT_IRQ2: ViUInt32 = 2;
pub const VI_ASSERT_IRQ3: ViUInt32 = 3;
pub const VI_ASSERT_IRQ4: ViUInt32 = 4;
pub const VI_ASSERT_IRQ5: ViUInt32 = 5;
pub const VI_ASSERT_IRQ6: ViUInt32 = 6;
pub const VI_ASSERT_IRQ7: ViUInt32 = 7;
pub const VI_UTIL_ASSERT_SYSRESET: ViUInt32 = 1;
pub const VI_UTIL_ASSERT_SYSFAIL: ViUInt32 = 2;
pub const VI_UTIL_DEASSERT_SYSFAIL: ViUInt32 = 3;
pub const VI_VXI_CLASS_MEMORY: ViUInt32 = 0;
pub const VI_VXI_CLASS_EXTENDED: ViUInt32 = 1;
pub const VI_VXI_CLASS_MESSAGE: ViUInt32 = 2;
pub const VI_VXI_CLASS_REGISTER: ViUInt32 = 3;
pub const VI_VXI_CLASS_OTHER: ViUInt32 = 4;
pub const VI_PXI_ADDR_NONE: ViUInt32 = 0;
pub const VI_PXI_ADDR_MEM: ViUInt32 = 1;
pub const VI_PXI_ADDR_IO: ViUInt32 = 2;
pub const VI_PXI_ADDR_CFG: ViUInt32 = 3;
pub const VI_TRIG_UNKNOWN: ViInt32 = -1;
pub const VI_PXI_LBUS_STAR_TRIG_BUS_0: ViUInt32 = 1000;
pub const VI_PXI_LBUS_STAR_TRIG_BUS_1: ViUInt32 = 1001;
pub const VI_PXI_LBUS_STAR_TRIG_BUS_2: ViUInt32 = 1002;
pub const VI_PXI_LBUS_STAR_TRIG_BUS_3: ViUInt32 = 1003;
pub const VI_PXI_LBUS_STAR_TRIG_BUS_4: ViUInt32 = 1004;
pub const VI_PXI_LBUS_STAR_TRIG_BUS_5: ViUInt32 = 1005;
pub const VI_PXI_LBUS_STAR_TRIG_BUS_6: ViUInt32 = 1006;
pub const VI_PXI_LBUS_STAR_TRIG_BUS_7: ViUInt32 = 1007;
pub const VI_PXI_LBUS_STAR_TRIG_BUS_8: ViUInt32 = 1008;
pub const VI_PXI_LBUS_STAR_TRIG_BUS_9: ViUInt32 = 1009;
pub const VI_PXI_STAR_TRIG_CONTROLLER: ViUInt32 = 1413;
pub const VI_ERROR_INV_SESSION: ViInt32 = -1073807346;
pub const VI_INFINITE: ViUInt32 = 4294967295;
pub const VI_NORMAL: ViUInt32 = 1;
pub const VI_FDC: ViUInt32 = 2;
pub const VI_HS488: ViUInt32 = 3;
pub const VI_ASRL488: ViUInt32 = 4;
pub const VI_ASRL_IN_BUF: ViUInt32 = 16;
pub const VI_ASRL_OUT_BUF: ViUInt32 = 32;
pub const VI_ASRL_IN_BUF_DISCARD: ViUInt32 = 64;
pub const VI_ASRL_OUT_BUF_DISCARD: ViUInt32 = 128;
pub type va_list = __builtin_va_list;
pub type __gnuc_va_list = __builtin_va_list;

// !!!
macro_rules! c_macros_to_rust_consts {
    ($(#define $name:ident ($value:ident))*) => {
        $(pub const $name: ViUInt32 = $value;)*
    };
}

#[cfg(target_pointer_width = "64")]
c_macros_to_rust_consts! {
    #define VI_ATTR_USER_DATA (VI_ATTR_USER_DATA_64)
    #define VI_ATTR_RET_COUNT (VI_ATTR_RET_COUNT_64)
    #define VI_ATTR_WIN_BASE_ADDR (VI_ATTR_WIN_BASE_ADDR_64)
    #define VI_ATTR_WIN_SIZE (VI_ATTR_WIN_SIZE_64)
    #define VI_ATTR_MEM_BASE (VI_ATTR_MEM_BASE_64)
    #define VI_ATTR_MEM_SIZE (VI_ATTR_MEM_SIZE_64)
    #define VI_ATTR_PXI_MEM_BASE_BAR0 (VI_ATTR_PXI_MEM_BASE_BAR0_64)
    #define VI_ATTR_PXI_MEM_BASE_BAR1 (VI_ATTR_PXI_MEM_BASE_BAR1_64)
    #define VI_ATTR_PXI_MEM_BASE_BAR2 (VI_ATTR_PXI_MEM_BASE_BAR2_64)
    #define VI_ATTR_PXI_MEM_BASE_BAR3 (VI_ATTR_PXI_MEM_BASE_BAR3_64)
    #define VI_ATTR_PXI_MEM_BASE_BAR4 (VI_ATTR_PXI_MEM_BASE_BAR4_64)
    #define VI_ATTR_PXI_MEM_BASE_BAR5 (VI_ATTR_PXI_MEM_BASE_BAR5_64)
    #define VI_ATTR_PXI_MEM_SIZE_BAR0 (VI_ATTR_PXI_MEM_SIZE_BAR0_64)
    #define VI_ATTR_PXI_MEM_SIZE_BAR1 (VI_ATTR_PXI_MEM_SIZE_BAR1_64)
    #define VI_ATTR_PXI_MEM_SIZE_BAR2 (VI_ATTR_PXI_MEM_SIZE_BAR2_64)
    #define VI_ATTR_PXI_MEM_SIZE_BAR3 (VI_ATTR_PXI_MEM_SIZE_BAR3_64)
    #define VI_ATTR_PXI_MEM_SIZE_BAR4 (VI_ATTR_PXI_MEM_SIZE_BAR4_64)
    #define VI_ATTR_PXI_MEM_SIZE_BAR5 (VI_ATTR_PXI_MEM_SIZE_BAR5_64)
}

#[cfg(not(target_pointer_width = "64"))]
c_macros_to_rust_consts! {
    #define VI_ATTR_USER_DATA (VI_ATTR_USER_DATA_32)
    #define VI_ATTR_RET_COUNT (VI_ATTR_RET_COUNT_32)
    #define VI_ATTR_WIN_BASE_ADDR (VI_ATTR_WIN_BASE_ADDR_32)
    #define VI_ATTR_WIN_SIZE (VI_ATTR_WIN_SIZE_32)
    #define VI_ATTR_MEM_BASE (VI_ATTR_MEM_BASE_32)
    #define VI_ATTR_MEM_SIZE (VI_ATTR_MEM_SIZE_32)
    #define VI_ATTR_PXI_MEM_BASE_BAR0 (VI_ATTR_PXI_MEM_BASE_BAR0_32)
    #define VI_ATTR_PXI_MEM_BASE_BAR1 (VI_ATTR_PXI_MEM_BASE_BAR1_32)
    #define VI_ATTR_PXI_MEM_BASE_BAR2 (VI_ATTR_PXI_MEM_BASE_BAR2_32)
    #define VI_ATTR_PXI_MEM_BASE_BAR3 (VI_ATTR_PXI_MEM_BASE_BAR3_32)
    #define VI_ATTR_PXI_MEM_BASE_BAR4 (VI_ATTR_PXI_MEM_BASE_BAR4_32)
    #define VI_ATTR_PXI_MEM_BASE_BAR5 (VI_ATTR_PXI_MEM_BASE_BAR5_32)
    #define VI_ATTR_PXI_MEM_SIZE_BAR0 (VI_ATTR_PXI_MEM_SIZE_BAR0_32)
    #define VI_ATTR_PXI_MEM_SIZE_BAR1 (VI_ATTR_PXI_MEM_SIZE_BAR1_32)
    #define VI_ATTR_PXI_MEM_SIZE_BAR2 (VI_ATTR_PXI_MEM_SIZE_BAR2_32)
    #define VI_ATTR_PXI_MEM_SIZE_BAR3 (VI_ATTR_PXI_MEM_SIZE_BAR3_32)
    #define VI_ATTR_PXI_MEM_SIZE_BAR4 (VI_ATTR_PXI_MEM_SIZE_BAR4_32)
    #define VI_ATTR_PXI_MEM_SIZE_BAR5 (VI_ATTR_PXI_MEM_SIZE_BAR5_32)
}

// !!!

/// A UInt that is the same size as the target's pointer width
// !!!
#[cfg(target_pointer_width = "64")]
pub type ViUIntPtrSize = ViUInt64;
#[cfg(not(target_pointer_width = "64"))]
pub type ViUIntPtrSize = ViUInt32;
// !!!

pub type ViUInt64 = ::std::os::raw::c_ulonglong;
pub type ViInt64 = ::std::os::raw::c_longlong;
pub type ViPUInt64 = *mut ViUInt64;
pub type ViAUInt64 = *mut ViUInt64;
pub type ViPInt64 = *mut ViInt64;
pub type ViAInt64 = *mut ViInt64;
pub type ViUInt32 = ::std::os::raw::c_ulong;
pub type ViPUInt32 = *mut ViUInt32;
pub type ViAUInt32 = *mut ViUInt32;
pub type ViInt32 = ::std::os::raw::c_long;
pub type ViPInt32 = *mut ViInt32;
pub type ViAInt32 = *mut ViInt32;
pub type ViUInt16 = ::std::os::raw::c_ushort;
pub type ViPUInt16 = *mut ViUInt16;
pub type ViAUInt16 = *mut ViUInt16;
pub type ViInt16 = ::std::os::raw::c_short;
pub type ViPInt16 = *mut ViInt16;
pub type ViAInt16 = *mut ViInt16;
pub type ViUInt8 = ::std::os::raw::c_uchar;
pub type ViPUInt8 = *mut ViUInt8;
pub type ViAUInt8 = *mut ViUInt8;
pub type ViInt8 = ::std::os::raw::c_schar;
pub type ViPInt8 = *mut ViInt8;
pub type ViAInt8 = *mut ViInt8;
pub type ViChar = ::std::os::raw::c_char;
pub type ViPChar = *mut ViChar;
pub type ViAChar = *mut ViChar;
pub type ViByte = ::std::os::raw::c_uchar;
pub type ViPByte = *mut ViByte;
pub type ViAByte = *mut ViByte;
pub type ViAddr = *mut ::std::os::raw::c_void;
pub type ViPAddr = *mut ViAddr;
pub type ViAAddr = *mut ViAddr;
pub type ViReal32 = f32;
pub type ViPReal32 = *mut ViReal32;
pub type ViAReal32 = *mut ViReal32;
pub type ViReal64 = f64;
pub type ViPReal64 = *mut ViReal64;
pub type ViAReal64 = *mut ViReal64;
pub type ViBuf = ViPByte;
pub type ViConstBuf = *const ViByte;
pub type ViPBuf = ViPByte;
pub type ViABuf = *mut ViPByte;
pub type ViString = ViPChar;
pub type ViConstString = *const ViChar;
pub type ViPString = ViPChar;
pub type ViAString = *mut ViPChar;
pub type ViRsrc = ViString;
pub type ViConstRsrc = ViConstString;
pub type ViPRsrc = ViString;
pub type ViARsrc = *mut ViString;
pub type ViBoolean = ViUInt16;
pub type ViPBoolean = *mut ViBoolean;
pub type ViABoolean = *mut ViBoolean;
pub type ViStatus = ViInt32;
pub type ViPStatus = *mut ViStatus;
pub type ViAStatus = *mut ViStatus;
pub type ViVersion = ViUInt32;
pub type ViPVersion = *mut ViVersion;
pub type ViAVersion = *mut ViVersion;
pub type ViObject = ViUInt32;
pub type ViPObject = *mut ViObject;
pub type ViAObject = *mut ViObject;
pub type ViSession = ViObject;
pub type ViPSession = *mut ViSession;
pub type ViASession = *mut ViSession;
pub type ViAttr = ViUInt32;
pub type ViEvent = ViObject;
pub type ViPEvent = *mut ViEvent;
pub type ViFindList = ViObject;
pub type ViPFindList = *mut ViFindList;
// !!!
pub type ViBusAddress = ViUIntPtrSize;
pub type ViBusSize = ViUIntPtrSize;
pub type ViAttrState = ViUIntPtrSize;
// !!!
pub type ViBusAddress64 = ViUInt64;
pub type ViPBusAddress64 = *mut ViBusAddress64;
pub type ViEventType = ViUInt32;
pub type ViPEventType = *mut ViEventType;
pub type ViAEventType = *mut ViEventType;
pub type ViPAttrState = *mut ::std::os::raw::c_void;
pub type ViPAttr = *mut ViAttr;
pub type ViAAttr = *mut ViAttr;
pub type ViKeyId = ViString;
pub type ViConstKeyId = ViConstString;
pub type ViPKeyId = ViPString;
pub type ViJobId = ViUInt32;
pub type ViPJobId = *mut ViJobId;
pub type ViAccessMode = ViUInt32;
pub type ViPAccessMode = *mut ViAccessMode;
pub type ViPBusAddress = *mut ViBusAddress;
pub type ViEventFilter = ViUInt32;
pub type ViVAList = va_list;
pub type ViHndlr = ::std::option::Option<
    unsafe extern "system" fn(
        vi: ViSession,
        eventType: ViEventType,
        event: ViEvent,
        userHandle: ViAddr,
    ) -> ViStatus,
>;
extern "system" {
    pub fn viOpenDefaultRM(vi: ViPSession) -> ViStatus;
}
extern "system" {
    pub fn viFindRsrc(
        sesn: ViSession,
        expr: ViConstString,
        vi: ViPFindList,
        retCnt: ViPUInt32,
        desc: *mut ViChar,
    ) -> ViStatus;
}
extern "system" {
    pub fn viFindNext(vi: ViFindList, desc: *mut ViChar) -> ViStatus;
}
extern "system" {
    pub fn viParseRsrc(
        rmSesn: ViSession,
        rsrcName: ViConstRsrc,
        intfType: ViPUInt16,
        intfNum: ViPUInt16,
    ) -> ViStatus;
}
extern "system" {
    pub fn viParseRsrcEx(
        rmSesn: ViSession,
        rsrcName: ViConstRsrc,
        intfType: ViPUInt16,
        intfNum: ViPUInt16,
        rsrcClass: *mut ViChar,
        expandedUnaliasedName: *mut ViChar,
        aliasIfExists: *mut ViChar,
    ) -> ViStatus;
}
extern "system" {
    pub fn viOpen(
        sesn: ViSession,
        name: ViConstRsrc,
        mode: ViAccessMode,
        timeout: ViUInt32,
        vi: ViPSession,
    ) -> ViStatus;
}
extern "system" {
    pub fn viClose(vi: ViObject) -> ViStatus;
}
extern "system" {
    pub fn viSetAttribute(vi: ViObject, attrName: ViAttr, attrValue: ViAttrState) -> ViStatus;
}
extern "system" {
    pub fn viGetAttribute(
        vi: ViObject,
        attrName: ViAttr,
        attrValue: *mut ::std::os::raw::c_void,
    ) -> ViStatus;
}
extern "system" {
    pub fn viStatusDesc(vi: ViObject, status: ViStatus, desc: *mut ViChar) -> ViStatus;
}
extern "system" {
    pub fn viTerminate(vi: ViObject, degree: ViUInt16, jobId: ViJobId) -> ViStatus;
}
extern "system" {
    pub fn viLock(
        vi: ViSession,
        lockType: ViAccessMode,
        timeout: ViUInt32,
        requestedKey: ViConstKeyId,
        accessKey: *mut ViChar,
    ) -> ViStatus;
}
extern "system" {
    pub fn viUnlock(vi: ViSession) -> ViStatus;
}
extern "system" {
    pub fn viEnableEvent(
        vi: ViSession,
        eventType: ViEventType,
        mechanism: ViUInt16,
        context: ViEventFilter,
    ) -> ViStatus;
}
extern "system" {
    pub fn viDisableEvent(vi: ViSession, eventType: ViEventType, mechanism: ViUInt16) -> ViStatus;
}
extern "system" {
    pub fn viDiscardEvents(vi: ViSession, eventType: ViEventType, mechanism: ViUInt16) -> ViStatus;
}
extern "system" {
    pub fn viWaitOnEvent(
        vi: ViSession,
        inEventType: ViEventType,
        timeout: ViUInt32,
        outEventType: ViPEventType,
        outContext: ViPEvent,
    ) -> ViStatus;
}
extern "system" {
    pub fn viInstallHandler(
        vi: ViSession,
        eventType: ViEventType,
        handler: ViHndlr,
        userHandle: ViAddr,
    ) -> ViStatus;
}
extern "system" {
    pub fn viUninstallHandler(
        vi: ViSession,
        eventType: ViEventType,
        handler: ViHndlr,
        userHandle: ViAddr,
    ) -> ViStatus;
}
extern "system" {
    pub fn viRead(vi: ViSession, buf: ViPBuf, cnt: ViUInt32, retCnt: ViPUInt32) -> ViStatus;
}
extern "system" {
    pub fn viReadAsync(vi: ViSession, buf: ViPBuf, cnt: ViUInt32, jobId: ViPJobId) -> ViStatus;
}
extern "system" {
    pub fn viReadToFile(
        vi: ViSession,
        filename: ViConstString,
        cnt: ViUInt32,
        retCnt: ViPUInt32,
    ) -> ViStatus;
}
extern "system" {
    pub fn viWrite(vi: ViSession, buf: ViConstBuf, cnt: ViUInt32, retCnt: ViPUInt32) -> ViStatus;
}
extern "system" {
    pub fn viWriteAsync(vi: ViSession, buf: ViConstBuf, cnt: ViUInt32, jobId: ViPJobId)
        -> ViStatus;
}
extern "system" {
    pub fn viWriteFromFile(
        vi: ViSession,
        filename: ViConstString,
        cnt: ViUInt32,
        retCnt: ViPUInt32,
    ) -> ViStatus;
}
extern "system" {
    pub fn viAssertTrigger(vi: ViSession, protocol: ViUInt16) -> ViStatus;
}
extern "system" {
    pub fn viReadSTB(vi: ViSession, status: ViPUInt16) -> ViStatus;
}
extern "system" {
    pub fn viClear(vi: ViSession) -> ViStatus;
}
extern "system" {
    pub fn viSetBuf(vi: ViSession, mask: ViUInt16, size: ViUInt32) -> ViStatus;
}
extern "system" {
    pub fn viFlush(vi: ViSession, mask: ViUInt16) -> ViStatus;
}
extern "system" {
    pub fn viBufWrite(vi: ViSession, buf: ViConstBuf, cnt: ViUInt32, retCnt: ViPUInt32)
        -> ViStatus;
}
extern "system" {
    pub fn viBufRead(vi: ViSession, buf: ViPBuf, cnt: ViUInt32, retCnt: ViPUInt32) -> ViStatus;
}
extern "C" {
    pub fn viPrintf(vi: ViSession, writeFmt: ViConstString, ...) -> ViStatus;
}
extern "system" {
    pub fn viVPrintf(vi: ViSession, writeFmt: ViConstString, params: ViVAList) -> ViStatus;
}
extern "C" {
    pub fn viSPrintf(vi: ViSession, buf: ViPBuf, writeFmt: ViConstString, ...) -> ViStatus;
}
extern "system" {
    pub fn viVSPrintf(
        vi: ViSession,
        buf: ViPBuf,
        writeFmt: ViConstString,
        parms: ViVAList,
    ) -> ViStatus;
}
extern "C" {
    pub fn viScanf(vi: ViSession, readFmt: ViConstString, ...) -> ViStatus;
}
extern "system" {
    pub fn viVScanf(vi: ViSession, readFmt: ViConstString, params: ViVAList) -> ViStatus;
}
extern "C" {
    pub fn viSScanf(vi: ViSession, buf: ViConstBuf, readFmt: ViConstString, ...) -> ViStatus;
}
extern "system" {
    pub fn viVSScanf(
        vi: ViSession,
        buf: ViConstBuf,
        readFmt: ViConstString,
        parms: ViVAList,
    ) -> ViStatus;
}
extern "C" {
    pub fn viQueryf(
        vi: ViSession,
        writeFmt: ViConstString,
        readFmt: ViConstString,
        ...
    ) -> ViStatus;
}
extern "system" {
    pub fn viVQueryf(
        vi: ViSession,
        writeFmt: ViConstString,
        readFmt: ViConstString,
        params: ViVAList,
    ) -> ViStatus;
}
extern "system" {
    pub fn viIn8(vi: ViSession, space: ViUInt16, offset: ViBusAddress, val8: ViPUInt8) -> ViStatus;
}
extern "system" {
    pub fn viOut8(vi: ViSession, space: ViUInt16, offset: ViBusAddress, val8: ViUInt8) -> ViStatus;
}
extern "system" {
    pub fn viIn16(
        vi: ViSession,
        space: ViUInt16,
        offset: ViBusAddress,
        val16: ViPUInt16,
    ) -> ViStatus;
}
extern "system" {
    pub fn viOut16(
        vi: ViSession,
        space: ViUInt16,
        offset: ViBusAddress,
        val16: ViUInt16,
    ) -> ViStatus;
}
extern "system" {
    pub fn viIn32(
        vi: ViSession,
        space: ViUInt16,
        offset: ViBusAddress,
        val32: ViPUInt32,
    ) -> ViStatus;
}
extern "system" {
    pub fn viOut32(
        vi: ViSession,
        space: ViUInt16,
        offset: ViBusAddress,
        val32: ViUInt32,
    ) -> ViStatus;
}
extern "system" {
    pub fn viIn64(
        vi: ViSession,
        space: ViUInt16,
        offset: ViBusAddress,
        val64: ViPUInt64,
    ) -> ViStatus;
}
extern "system" {
    pub fn viOut64(
        vi: ViSession,
        space: ViUInt16,
        offset: ViBusAddress,
        val64: ViUInt64,
    ) -> ViStatus;
}
extern "system" {
    pub fn viIn8Ex(
        vi: ViSession,
        space: ViUInt16,
        offset: ViBusAddress64,
        val8: ViPUInt8,
    ) -> ViStatus;
}
extern "system" {
    pub fn viOut8Ex(
        vi: ViSession,
        space: ViUInt16,
        offset: ViBusAddress64,
        val8: ViUInt8,
    ) -> ViStatus;
}
extern "system" {
    pub fn viIn16Ex(
        vi: ViSession,
        space: ViUInt16,
        offset: ViBusAddress64,
        val16: ViPUInt16,
    ) -> ViStatus;
}
extern "system" {
    pub fn viOut16Ex(
        vi: ViSession,
        space: ViUInt16,
        offset: ViBusAddress64,
        val16: ViUInt16,
    ) -> ViStatus;
}
extern "system" {
    pub fn viIn32Ex(
        vi: ViSession,
        space: ViUInt16,
        offset: ViBusAddress64,
        val32: ViPUInt32,
    ) -> ViStatus;
}
extern "system" {
    pub fn viOut32Ex(
        vi: ViSession,
        space: ViUInt16,
        offset: ViBusAddress64,
        val32: ViUInt32,
    ) -> ViStatus;
}
extern "system" {
    pub fn viIn64Ex(
        vi: ViSession,
        space: ViUInt16,
        offset: ViBusAddress64,
        val64: ViPUInt64,
    ) -> ViStatus;
}
extern "system" {
    pub fn viOut64Ex(
        vi: ViSession,
        space: ViUInt16,
        offset: ViBusAddress64,
        val64: ViUInt64,
    ) -> ViStatus;
}
extern "system" {
    pub fn viMoveIn8(
        vi: ViSession,
        space: ViUInt16,
        offset: ViBusAddress,
        length: ViBusSize,
        buf8: ViAUInt8,
    ) -> ViStatus;
}
extern "system" {
    pub fn viMoveOut8(
        vi: ViSession,
        space: ViUInt16,
        offset: ViBusAddress,
        length: ViBusSize,
        buf8: ViAUInt8,
    ) -> ViStatus;
}
extern "system" {
    pub fn viMoveIn16(
        vi: ViSession,
        space: ViUInt16,
        offset: ViBusAddress,
        length: ViBusSize,
        buf16: ViAUInt16,
    ) -> ViStatus;
}
extern "system" {
    pub fn viMoveOut16(
        vi: ViSession,
        space: ViUInt16,
        offset: ViBusAddress,
        length: ViBusSize,
        buf16: ViAUInt16,
    ) -> ViStatus;
}
extern "system" {
    pub fn viMoveIn32(
        vi: ViSession,
        space: ViUInt16,
        offset: ViBusAddress,
        length: ViBusSize,
        buf32: ViAUInt32,
    ) -> ViStatus;
}
extern "system" {
    pub fn viMoveOut32(
        vi: ViSession,
        space: ViUInt16,
        offset: ViBusAddress,
        length: ViBusSize,
        buf32: ViAUInt32,
    ) -> ViStatus;
}
extern "system" {
    pub fn viMoveIn64(
        vi: ViSession,
        space: ViUInt16,
        offset: ViBusAddress,
        length: ViBusSize,
        buf64: ViAUInt64,
    ) -> ViStatus;
}
extern "system" {
    pub fn viMoveOut64(
        vi: ViSession,
        space: ViUInt16,
        offset: ViBusAddress,
        length: ViBusSize,
        buf64: ViAUInt64,
    ) -> ViStatus;
}
extern "system" {
    pub fn viMoveIn8Ex(
        vi: ViSession,
        space: ViUInt16,
        offset: ViBusAddress64,
        length: ViBusSize,
        buf8: ViAUInt8,
    ) -> ViStatus;
}
extern "system" {
    pub fn viMoveOut8Ex(
        vi: ViSession,
        space: ViUInt16,
        offset: ViBusAddress64,
        length: ViBusSize,
        buf8: ViAUInt8,
    ) -> ViStatus;
}
extern "system" {
    pub fn viMoveIn16Ex(
        vi: ViSession,
        space: ViUInt16,
        offset: ViBusAddress64,
        length: ViBusSize,
        buf16: ViAUInt16,
    ) -> ViStatus;
}
extern "system" {
    pub fn viMoveOut16Ex(
        vi: ViSession,
        space: ViUInt16,
        offset: ViBusAddress64,
        length: ViBusSize,
        buf16: ViAUInt16,
    ) -> ViStatus;
}
extern "system" {
    pub fn viMoveIn32Ex(
        vi: ViSession,
        space: ViUInt16,
        offset: ViBusAddress64,
        length: ViBusSize,
        buf32: ViAUInt32,
    ) -> ViStatus;
}
extern "system" {
    pub fn viMoveOut32Ex(
        vi: ViSession,
        space: ViUInt16,
        offset: ViBusAddress64,
        length: ViBusSize,
        buf32: ViAUInt32,
    ) -> ViStatus;
}
extern "system" {
    pub fn viMoveIn64Ex(
        vi: ViSession,
        space: ViUInt16,
        offset: ViBusAddress64,
        length: ViBusSize,
        buf64: ViAUInt64,
    ) -> ViStatus;
}
extern "system" {
    pub fn viMoveOut64Ex(
        vi: ViSession,
        space: ViUInt16,
        offset: ViBusAddress64,
        length: ViBusSize,
        buf64: ViAUInt64,
    ) -> ViStatus;
}
extern "system" {
    pub fn viMove(
        vi: ViSession,
        srcSpace: ViUInt16,
        srcOffset: ViBusAddress,
        srcWidth: ViUInt16,
        destSpace: ViUInt16,
        destOffset: ViBusAddress,
        destWidth: ViUInt16,
        srcLength: ViBusSize,
    ) -> ViStatus;
}
extern "system" {
    pub fn viMoveAsync(
        vi: ViSession,
        srcSpace: ViUInt16,
        srcOffset: ViBusAddress,
        srcWidth: ViUInt16,
        destSpace: ViUInt16,
        destOffset: ViBusAddress,
        destWidth: ViUInt16,
        srcLength: ViBusSize,
        jobId: ViPJobId,
    ) -> ViStatus;
}
extern "system" {
    pub fn viMoveEx(
        vi: ViSession,
        srcSpace: ViUInt16,
        srcOffset: ViBusAddress64,
        srcWidth: ViUInt16,
        destSpace: ViUInt16,
        destOffset: ViBusAddress64,
        destWidth: ViUInt16,
        srcLength: ViBusSize,
    ) -> ViStatus;
}
extern "system" {
    pub fn viMoveAsyncEx(
        vi: ViSession,
        srcSpace: ViUInt16,
        srcOffset: ViBusAddress64,
        srcWidth: ViUInt16,
        destSpace: ViUInt16,
        destOffset: ViBusAddress64,
        destWidth: ViUInt16,
        srcLength: ViBusSize,
        jobId: ViPJobId,
    ) -> ViStatus;
}
extern "system" {
    pub fn viMapAddress(
        vi: ViSession,
        mapSpace: ViUInt16,
        mapOffset: ViBusAddress,
        mapSize: ViBusSize,
        access: ViBoolean,
        suggested: ViAddr,
        address: ViPAddr,
    ) -> ViStatus;
}
extern "system" {
    pub fn viUnmapAddress(vi: ViSession) -> ViStatus;
}
extern "system" {
    pub fn viMapAddressEx(
        vi: ViSession,
        mapSpace: ViUInt16,
        mapOffset: ViBusAddress64,
        mapSize: ViBusSize,
        access: ViBoolean,
        suggested: ViAddr,
        address: ViPAddr,
    ) -> ViStatus;
}
extern "system" {
    pub fn viPeek8(vi: ViSession, address: ViAddr, val8: ViPUInt8);
}
extern "system" {
    pub fn viPoke8(vi: ViSession, address: ViAddr, val8: ViUInt8);
}
extern "system" {
    pub fn viPeek16(vi: ViSession, address: ViAddr, val16: ViPUInt16);
}
extern "system" {
    pub fn viPoke16(vi: ViSession, address: ViAddr, val16: ViUInt16);
}
extern "system" {
    pub fn viPeek32(vi: ViSession, address: ViAddr, val32: ViPUInt32);
}
extern "system" {
    pub fn viPoke32(vi: ViSession, address: ViAddr, val32: ViUInt32);
}
extern "system" {
    pub fn viPeek64(vi: ViSession, address: ViAddr, val64: ViPUInt64);
}
extern "system" {
    pub fn viPoke64(vi: ViSession, address: ViAddr, val64: ViUInt64);
}
extern "system" {
    pub fn viMemAlloc(vi: ViSession, size: ViBusSize, offset: ViPBusAddress) -> ViStatus;
}
extern "system" {
    pub fn viMemFree(vi: ViSession, offset: ViBusAddress) -> ViStatus;
}
extern "system" {
    pub fn viMemAllocEx(vi: ViSession, size: ViBusSize, offset: ViPBusAddress64) -> ViStatus;
}
extern "system" {
    pub fn viMemFreeEx(vi: ViSession, offset: ViBusAddress64) -> ViStatus;
}
extern "system" {
    pub fn viGpibControlREN(vi: ViSession, mode: ViUInt16) -> ViStatus;
}
extern "system" {
    pub fn viGpibControlATN(vi: ViSession, mode: ViUInt16) -> ViStatus;
}
extern "system" {
    pub fn viGpibSendIFC(vi: ViSession) -> ViStatus;
}
extern "system" {
    pub fn viGpibCommand(
        vi: ViSession,
        cmd: ViConstBuf,
        cnt: ViUInt32,
        retCnt: ViPUInt32,
    ) -> ViStatus;
}
extern "system" {
    pub fn viGpibPassControl(vi: ViSession, primAddr: ViUInt16, secAddr: ViUInt16) -> ViStatus;
}
extern "system" {
    pub fn viVxiCommandQuery(
        vi: ViSession,
        mode: ViUInt16,
        cmd: ViUInt32,
        response: ViPUInt32,
    ) -> ViStatus;
}
extern "system" {
    pub fn viAssertUtilSignal(vi: ViSession, line: ViUInt16) -> ViStatus;
}
extern "system" {
    pub fn viAssertIntrSignal(vi: ViSession, mode: ViInt16, statusID: ViUInt32) -> ViStatus;
}
extern "system" {
    pub fn viMapTrigger(
        vi: ViSession,
        trigSrc: ViInt16,
        trigDest: ViInt16,
        mode: ViUInt16,
    ) -> ViStatus;
}
extern "system" {
    pub fn viUnmapTrigger(vi: ViSession, trigSrc: ViInt16, trigDest: ViInt16) -> ViStatus;
}
extern "system" {
    pub fn viUsbControlOut(
        vi: ViSession,
        bmRequestType: ViInt16,
        bRequest: ViInt16,
        wValue: ViUInt16,
        wIndex: ViUInt16,
        wLength: ViUInt16,
        buf: ViConstBuf,
    ) -> ViStatus;
}
extern "system" {
    pub fn viUsbControlIn(
        vi: ViSession,
        bmRequestType: ViInt16,
        bRequest: ViInt16,
        wValue: ViUInt16,
        wIndex: ViUInt16,
        wLength: ViUInt16,
        buf: ViPBuf,
        retCnt: ViPUInt16,
    ) -> ViStatus;
}
extern "system" {
    pub fn viPxiReserveTriggers(
        vi: ViSession,
        cnt: ViInt16,
        trigBuses: ViAInt16,
        trigLines: ViAInt16,
        failureIndex: ViPInt16,
    ) -> ViStatus;
}
pub type __builtin_va_list = *mut ::std::os::raw::c_char;
